### ISSUE TITLE
UI for MetaCom

### ISSUE THREAD

**Issue by GreatAndPowerfulKing** [metarhia/MetaCom-iOS#1]
UI for the first version of MetaCom will be created according to the referenced mock (see [metarhia/Metarhia#9 (comment)](https://github.com/metarhia/Metarhia/issues/9#issuecomment-301899303)). @GYFK, what do you think? Do we need to create app design in Sketch? Or we can start creating layouts for application in Interface Builder?

**Comment by GYFK** [comment]
@GreatAndPowerfulKing we are targeting a rather simple GUI for MetaCom chat. So in my opinion controls that were presented in the mock will suffice in creating a basic GUI. 
My idea is that we should develop a more or less functional GUI prototype via IB and that would be enough for the current version. If you are having some questions relating the mock, you are free to ask them here or create separate issues.
