### ISSUE TITLE
Save host:port locally

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaCom-iOS#13]
I don't know does it implemented for iOS app? @GYFK 
See android issue: https://github.com/metarhia/metacom-android/issues/7

**Comment by GYFK** [comment]
@tshemsedinov accidentally closed the issue in metacom-android. Yet the functionality is implemented.

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Should we add storing all successfully used "host:port" pairs and automatic connection to latest server on application launching as it was discussed in [metarhia/metacom-android#7](https://github.com/metarhia/metacom-android/issues/7)?

**Comment by tshemsedinov** [comment]
@GreatAndPowerfulKing @GYFK I think yes

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Ok, I'll work on it, if @GYFK has no objections.

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov But iOS doesn't provide out of the box solution for autocompletion in text fields like Android does. So it would be easier to add one more view with the list and search. Is it ok?
