### ISSUE TITLE
MetaCom logo

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaCom-iOS#14]
We need white logo on black. This is not Metarhia logo, this is solar eclipse:
![mc](https://user-images.githubusercontent.com/4405297/30458146-fa970c36-99b2-11e7-9301-b7dfc6b507da.png)

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov If we will use original Metarhia logo (white circle with black shadow) it will looks like just white circle on a black background:
![30458146-fa970c36-99b2-11e7-9301-b7dfc6b507da](https://user-images.githubusercontent.com/17301178/30458611-03cd92c8-99b5-11e7-87ed-9b97de9c1449.png)

Is it ok?

**Comment by tshemsedinov** [comment]
Exactly! And that's great and powerful @GreatAndPowerfulKing

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Ok. I will also update app icon according to this modification.

**Comment by tshemsedinov** [comment]
Here are logos: https://github.com/metarhia/Metarhia/blob/master/Logos/
Vector [svg](https://github.com/metarhia/Metarhia/blob/master/Logos/metarhia-logo.svg) logos are preferred but we have rendered previews with [white](https://github.com/metarhia/Metarhia/blob/master/Logos/metarhia-logo-on-white.png) and [black](https://github.com/metarhia/Metarhia/blob/master/Logos/metarhia-logo-on-black.png) backgrounds.
@GreatAndPowerfulKing @lidaamber @GYFK

**Comment by GYFK** [comment]
@tshemsedinov IMHO but that is not metarhia logo also. That is just a white circle. In metacom-ios we use inverted metarhia logo to fit the general theme of the application. We tend to leave it as is. Yet the final decision is up to you.
