### ISSUE TITLE
Chat export

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaCom-iOS#15]
We need new functionality: before exit user may want to save history to the text file.
For iOS all files should be stored attached to certain application, so I think we will not store files attached to Metacom. Better export to different apps (registered in system), cloud storage apps, etc. @GYFK

**Comment by GreatAndPowerfulKing** [comment]
Okay. If @GYFK has no objections, I'll work on it.

So, there are some questions about the file's structure:
- how to name interlocutors? (e. g. "Me" and "Other")
- how should we represent files transfers in exported text?

**Comment by tshemsedinov** [comment]
- me and other is ok
- file transfer should be represented as in chat screen

**Comment by GYFK** [comment]
@GreatAndPowerfulKing LGTM
