### ISSUE TITLE
Message class modification

### ISSUE THREAD

**Issue by GreatAndPowerfulKing** [metarhia/MetaCom-iOS#5]
I propose to replace `MessageType` in  [Message class](https://github.com/metarhia/MetaCom-iOS/blob/master/MetaCom-iOS/Core/Models/Message.swift) with an `enum` with associated values, something like this (it's only concept and should be discussed):
``` Swift
public enum Content {
	case text(String)
	case image(UIImage)
	case file(Data)
}
```
Remove property `type` and replace `let content: String` with `let content: Content`. 

@GYFK If you are agree, I'm ready to work on this modification.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing sure, that would really be better.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK Okay. Then we should decide which data types will be supported for displaying in chat "on the fly" and which will be processed like a generic `file`. If we will use [JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController) it supports images, audio and video files out of the box (but not generic data), but I suppose, we should agree the list of supporting file types with Android team.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing as far I suggest constraining content types to:
``` Swift
public enum Content {
	case text(String)
	case file(Data)
}
```
As basic functionality includes only saving and transferring the file between applications, but no file content previewing.
