### ISSUE TITLE
GUI for MetaCom

### ISSUE THREAD

**Issue by GreatAndPowerfulKing** [metarhia/MetaCom-iOS#6]
Current version of user interface looks like a prototype. It's not ugly, but not good at all. So I propose to try to create new pretty version of GUI based on a current navigation logic. I doubt that we will look for a graphical designer for this project, that's why I can try to do it myself, but only if you, @GYFK, will approve this task.

**Comment by tshemsedinov** [comment]
@GreatAndPowerfulKing No we do not need special design for this app, we need just simple GUI with common platform guidelines, default controls and nothing custom.

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Okay.

**Comment by tshemsedinov** [comment]
@metarhia/ios We need good UX and UI but I do not believe in designers. They are drawing custom an never use theirs own UI, so I think developers can do it better.

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov I'm not proposing to create all new custom controls and interfaces. Just to add maybe few colors and some background. For example, replace this:
![simulator screen shot 27 2017 01 26 03](https://cloud.githubusercontent.com/assets/17301178/26514754/9ce5a58a-427c-11e7-909e-1b032eb9218d.png)
with something like this (just example):
![img_1176](https://cloud.githubusercontent.com/assets/17301178/26514758/a2428d0e-427c-11e7-964c-5a7b9005224f.PNG)

I suppose it's a common and easy way to make app looks better and more user-friendly, but using default controls.

**Comment by aqrln** [comment]
@GreatAndPowerfulKing although I don't fully agree with the last @tshemsedinov's statement (but I see where he's coming from and what's his motivation to say so), regarding your example... well, in my opinion, the first screenshot definitely looks more beautiful 😄

**Comment by aqrln** [comment]
@GreatAndPowerfulKing though I do apprehend that it may be just a not well-turned example, and you have my +1 for using colors and solid or simple geometric backgrounds.

**Comment by GreatAndPowerfulKing** [comment]
@aqrln I completely agree with you that the first screenshot looks more clear, but the second is just hot midnight example 😅.

**Comment by tshemsedinov** [comment]
Don't turn an app into svistoperdelka, how it would be in English

**Comment by aqrln** [comment]
@tshemsedinov it's "bells and whistles" in English, fwiw ;)
