### ISSUE TITLE
Files selection for uploading

### ISSUE THREAD

**Issue by GreatAndPowerfulKing** [metarhia/MetaCom-iOS#7]
We should decide how user will select files for uploading. There are two common ways:
1. Add MetaCom to the system's share menu to accept any files:
![img_1199](https://cloud.githubusercontent.com/assets/17301178/26632917/5db88c8c-461a-11e7-833b-1b91defca811.PNG)

2. Allow user to select files from iCloud Drive:
![img_1200](https://cloud.githubusercontent.com/assets/17301178/26632923/612b9eae-461a-11e7-838c-c7d3ef26289c.PNG)

I suppose we should provide both options. 

The first one is a little bit complicated because we should handle file receiving in any point of an application’s lifecycle (e. g. if there is not an active connection, let user to setup it; or to specify a chatroom, if needed; etc).

The second one requires Apple ID enrolled into Apple Developer Program. So, it can be added later.

**Comment by tshemsedinov** [comment]
Yes, we need both, but @GreatAndPowerfulKing let's do it in simple way: if no connection or no chat, we can just show an error message. @metarhia/mobile

**Comment by GYFK** [comment]
@GreatAndPowerfulKing I would recommend against using the first approach, as it will definitely turn into mess with all that error showing or handling a state of connection and chat.

The second option seems far better. Yet it will be better to also give an opportunity to select standard Photos App item of any kind and maybe provide access to files from not only the iCloud Drive (which is a must), but also Google Drive and/or Dropbox. What do you think?

**Comment by Gagnant** [comment]
@GYFK, I think that both variants should exist. Is it a big difficulty to put all outgoing data in queue and send only after user established the connection (specified chatroom)?

**Comment by GreatAndPowerfulKing** [comment]
@GYFK I supposed that photos selection shouldn't even be discussed 😅. Of course this opportunity will be given to a user. 

Google Drive, Dropbox, Box, Mega etc. – yes, it's good idea but there are lots of such services and it's impossible to support all of them. So, I agree with @Gagnant that we should provide the first option too, it will make possible sharing from anywhere. It's not too difficult to store files while connection isn't ready to use. For more simplicity we can store only the last imported file and only while the app is alive (during a single run), but it's not a big deal to store any amount of files through multiple app launching (we just need not to forget to delete files after some timeout to prevent uncontrolled application's weight growing). 

I just think how to do it better in UI. Perhaps add a share option like "Select from queued", or something like this.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing no, as for the current version of the application we will implement only the second proposed variant. 
"Google Drive, Dropbox, Box, Mega etc." — we do not consider "etc" as for now. Supporting major services such as Google Drive, Dropbox and iCloud Drive will be more than enough.
We will probably consider implementing this feature in the future versions of application.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK Okay. Accepted.

**Comment by tshemsedinov** [comment]
Yes, we can do it step by step, because we need to publish minimal app ASAP
