### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by GreatAndPowerfulKing** [metarhia/MetaCom-iOS#9]
@GYFK I don't understand a purpose of `MessageReceiver` protocol. If only notification about new messages, then `didJoin()` and `didLeave()` methods are excessive. In other case, it shouldn't be called like `MessageReceiver`, but `ChatRoomDelegate`. Also mentioned above methods' names are too short and provide no info about the sender. I suppose we should follow delegate methods naming like `chatRoom(_ chat: ChatRoom, didReceiveMessage message: Message)`.

**Comment by GreatAndPowerfulKing** [comment]
Also we can replace such solution with `NotificationCenter` to follow the style used in `UserConnection`. Because currently two different patterns are applied for the same purpose in the single project.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing I agree with renaming a protocol and related methods. As for now that was done in https://github.com/metarhia/metacom-ios/commit/f70777dfdc35617f4d5a5d0b77e227f0da4a6c1d.

As for using two different patterns I can't really see something bad. ``NotificationCenter`` is used only in the ``Core`` functionality while delegate is mainly exposed to the application code.
